version: "3"
services:
  go:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
    - ..:/workspace:cached
